services:
  - type: web
    name: mathmaster-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mathmaster-db
          property: connectionString

databases:
  - name: mathmaster-db
    databaseName: mathmaster
    user: mathmaster
